### ISSUE TITLE
Create cluster fails because openshifter image is not found

### ISSUE THREAD

**Issue by galderz** [cmoulliard/gce-openshifter#1]
./create-cluster.sh cluster01                                                                                                                                            
    Unable to find image 'osevg/openshifter:15' locally
    docker: Error response from daemon: manifest for osevg/openshifter:15 not found.
    See 'docker run --help'.

**Comment by cmoulliard** [comment]
The image `osevg/openshifter:15` has been created some months by Marek as a work. I hope that now his work has been merged top of this image `https://hub.docker.com/r/osevg/openshifter/tags/`

Can you try it please ?

**Comment by galderz** [comment]
Try what? Only latest tag is available.

**Comment by marekjelen** [comment]
Yes, :15 was merged into :latest
